name: deployment

on:
  release:
    types: [created]
    
jobs:
  publish:
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v2
        with:
          node-version: 15.x
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-15.x-${{ hashFiles('**/package.json') }}
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.0
        with:
          version: 6.0.2
          run_install: true
      - name: Publish
        run: |
          pnpm run build
          pnpm run test
          pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          pnpm publish --ignore-scripts
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
